# Generated by Django 5.2.6 on 2025-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='humidity',
            field=models.IntegerField(),
        ),
    ]
